language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

jobs:
  include:
    - stage: lint
      script: cargo test --features "clippy"
      rust: nightly
