[package]
name = "git-interactive-rebase-tool"
version = "0.5.0"
authors = ["Tim Oram <mitmaro@gmail.com>"]
license = "ISC"
description = "Full feature terminal based sequence editor for git interactive rebase. Written in Rust using ncurses."
repository = "https://github.com/MitMaro/git-interactive-rebase-tool"
keywords = [ "git", "editor", "tool", "rebase", "interactive" ]
readme = "README.md"
include = [
    "**/*.rs",
    "Cargo.toml",
    "CHANGELOG.md",
    "LICENSE",
    "README.md"
]

[dependencies]
clippy = {version = "0.0.177", optional = true}
pancurses = "0.13"
pad = "0.1.4"

[features]
default = []

[package.metadata.deb]
maintainer = "Tim Oram <me@mitmaro.ca>"
copyright = "Tim Oram <me@mitmaro.ca>"
license_file = ["LICENSE", "2"]
extended_description = """\
Full feature terminal based sequence editor for git interactive rebase. Written in Rust using ncurses."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/git-interactive-rebase-tool", "usr/bin/interactive-rebase-tool", "755"],
    ["README.md", "usr/share/doc/cargo-deb/README", "644"],
    ["interactive-rebase-tool.1", "usr/share/man/man1/interactive-rebase-tool.1", "644"]
]
