[package]
name = "git-interactive-rebase-tool"
version = "0.2.0"
authors = ["Tim Oram <mitmaro@gmail.com>"]
license = "ISC"
description = "Full feature terminal based sequence editor for git interactive rebase. Written in Rust using ncurses."
repository = "https://github.com/MitMaro/git-interactive-rebase-tool"
keywords = [ "git", "editor", "tool", "rebase", "interactive", "ncurses" ]
readme = "README.md"

[dependencies]
pancurses = "0.7"
