[package]
name = "git-interactive-rebase-tool"
version = "0.6.0"
authors = [
    "Tim Oram <me@mitmaro.ca>",
    "Mark Stacey <markjstacey@gmail.com>",
    "Peter Deal <pdeal@nl.rogers.com>"
]
license = "ISC"
description = "Full feature terminal based sequence editor for git interactive rebase. Written in Rust using ncurses."
repository = "https://github.com/MitMaro/git-interactive-rebase-tool"
keywords = [ "git", "editor", "tool", "rebase", "interactive" ]
readme = "README.md"
include = [
    "**/*.rs",
    "Cargo.toml",
    "CHANGELOG.md",
    "LICENSE",
    "README.md"
]

[[bin]]
name = "interactive-rebase-tool"
path = "src/main.rs"

[dependencies]
clippy = {version = "0.0.191", optional = true}
pancurses = "0.15.0"
pad = "0.1.5"

[features]
default = []

[package.metadata.deb]
name = "interactive-rebase-tool"
maintainer = "Tim Oram <dev@mitmaro.ca>"
copyright = "Tim Oram <dev@mitmaro.ca>"
license-file = ["LICENSE", "2"]
extended-description = """\
Full feature terminal based sequence editor for git interactive rebase. Written in Rust using ncurses."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/interactive-rebase-tool", "usr/bin/interactive-rebase-tool", "755"],
    ["README.md", "usr/share/doc/cargo-deb/README", "644"],
    ["src/interactive-rebase-tool.1", "usr/share/man/man1/interactive-rebase-tool.1", "644"]
]
